# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: issue.proto
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0bissue.proto\x12\x11\x64unedaq.ersschema"\xe3\x01\n\x07\x43ontext\x12\x0b\n\x03\x63wd\x18\x01 \x01(\t\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\x15\n\rfunction_name\x18\x03 \x01(\t\x12\x11\n\thost_name\x18\x04 \x01(\t\x12\x13\n\x0bline_number\x18\x05 \x01(\r\x12\x14\n\x0cpackage_name\x18\x06 \x01(\t\x12\x12\n\nprocess_id\x18\x0b \x01(\r\x12\x11\n\tthread_id\x18\x0c \x01(\r\x12\x0f\n\x07user_id\x18\r \x01(\r\x12\x11\n\tuser_name\x18\x0e \x01(\t\x12\x18\n\x10\x61pplication_name\x18\x0f \x01(\t"\x85\x02\n\x0bSimpleIssue\x12+\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x1a.dunedaq.ersschema.Context\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0binheritance\x18\x03 \x03(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x10\n\x08severity\x18\x05 \x01(\t\x12\x0c\n\x04time\x18\x06 \x01(\x04\x12\x42\n\nparameters\x18\x0b \x03(\x0b\x32..dunedaq.ersschema.SimpleIssue.ParametersEntry\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"\xa1\x01\n\nIssueChain\x12-\n\x05\x66inal\x18\x01 \x01(\x0b\x32\x1e.dunedaq.ersschema.SimpleIssue\x12.\n\x06\x63\x61uses\x18\x02 \x03(\x0b\x32\x1e.dunedaq.ersschema.SimpleIssue\x12\x0f\n\x07session\x18\n \x01(\t\x12\x13\n\x0b\x61pplication\x18\x0b \x01(\t\x12\x0e\n\x06module\x18\x0c \x01(\tb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "issue_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _SIMPLEISSUE_PARAMETERSENTRY._options = None
    _SIMPLEISSUE_PARAMETERSENTRY._serialized_options = b"8\001"
    _globals["_CONTEXT"]._serialized_start = 35
    _globals["_CONTEXT"]._serialized_end = 262
    _globals["_SIMPLEISSUE"]._serialized_start = 265
    _globals["_SIMPLEISSUE"]._serialized_end = 526
    _globals["_SIMPLEISSUE_PARAMETERSENTRY"]._serialized_start = 477
    _globals["_SIMPLEISSUE_PARAMETERSENTRY"]._serialized_end = 526
    _globals["_ISSUECHAIN"]._serialized_start = 529
    _globals["_ISSUECHAIN"]._serialized_end = 690
# @@protoc_insertion_point(module_scope)
