site_name: Drunc UI

theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_nav.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            show_category_heading: true
            merge_init_into_class: true
          paths: [.]

nav:
  - Home: index.md
  - Code Overview: code_overview.md
  - Process Manager UI: process_manager.md
  - Controller UI: controller.md
  - Development: development.md
  - Code Reference: reference/
