site_name: Drunc UI

theme:
  name: material

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_nav.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            show_category_heading: true
            merge_init_into_class: true
          paths: [.]

nav:
  - Home: index.md
  - Code Reference: reference/
