apiVersion: batch/v1
kind: Job
metadata:
  name: django-staticfiles
  namespace: drunc-ui-app
spec:
  ttlSecondsAfterFinished: 100
  activeDeadlineSeconds: 60

  template:
    spec:
      volumes:
        - name: staticfiles
          persistentVolumeClaim:
            claimName: staticfiles-pvc
      containers:
        - name: staticfiles-container
          image: drunc_ui_app:latest
          command: [python, manage.py, collectstatic, --noinput]
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: app-cm
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: /data/static
              name: staticfiles
      restartPolicy: OnFailure
  backoffLimit: 3
