apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-deploy
  namespace: drunc-ui-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-application
  template:
    metadata:
      labels:
        app: django-application
    spec:
      volumes:
        - name: staticfiles
          persistentVolumeClaim:
            claimName: staticfiles-pvc
      containers:
        - name: django-app-container
          image: drunc_ui_app:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: app-cm
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: /data/static
              name: staticfiles
