# Generated by Django 5.1.3 on 2024-11-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_druncmessage_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='druncmessage',
            name='severity',
            field=models.CharField(choices=[('INFO', 'INFO'), ('CRITICAL', 'CRITICAL'), ('ERROR', 'ERROR'), ('DEBUG', 'DEBUG')], default='INFO', max_length=10),
        ),
    ]
