# Generated by Django 5.1.1 on 2024-11-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_druncmessage_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='druncmessage',
            name='severity',
            field=models.CharField(default='INFO', max_length=255),
        ),
    ]
