# Generated by Django 5.1.7 on 2025-04-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_druncmessage_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='druncmessage',
            name='severity',
            field=models.CharField(choices=[('INFO', 'INFO'), ('WARNING', 'WARNING'), ('FATAL', 'FATAL'), ('ERROR', 'ERROR'), ('DEBUG', 'DEBUG')], default='INFO', max_length=10),
        ),
    ]
