name: Test and build

on:
  push:
    branches: [main]
  pull_request:
  release:
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    container:
      image: ghcr.io/dune-daq/nightly-release-alma9:development_v5

    steps:
      - uses: actions/setup-python@v6
        with:
          python-version: 3.12

      - name: Set up dev nightly
        run: |
          mkdir nightly
          cd nightly
          . /cvmfs/dunedaq.opensciencegrid.org/setup_dunedaq.sh
          setup_dbt latest_v5
          dbt-create -n last_fddaq
          cd NFD_DEV*
          . env.shell
          dbt-build

      - uses: actions/checkout@v6

      - name: Install dependencies
        run: pip install .[dev,docs]

      - name: Run tests
        run: pytest --cov-report=xml

      - name: Upload coverage to Codecov
        if: success()
        uses: codecov/codecov-action@v6
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Test building the docs
        run: mkdocs build --strict
