name: Test and build

on:
  push:
    branches: [main]
  pull_request:
  release:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/dune-daq/nightly-release-alma9:development_v5

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v6

      - name: Set up dev nightly and run checks
        run: |
          set -eo pipefail

          mkdir nightly
          cd nightly

          . /cvmfs/dunedaq.opensciencegrid.org/setup_dunedaq.sh
          setup_dbt latest_v5
          dbt-create -n last_fddaq

          cd NFD_DEV*
          . env.sh

          dbt-build

          cd "$GITHUB_WORKSPACE"

          python3 -m pip install --upgrade pip
          python3 -m pip install '.[dev,docs]'

          python3 -m pytest --cov-report=xml
          python3 -m mkdocs build --strict

      - name: Upload coverage to Codecov
        if: success()
        uses: codecov/codecov-action@v6
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
