name: Test and build

on:
  workflow_call:
    inputs:
      python_version:
        description: Python version to use in the workflow
        default: '3.10'
        type: string
      use_develop:
        description: If develop versions of drunc and druncschema should be used
        default: false
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry==1.8.4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}
          cache: poetry

      - name: Install dependencies
        run: poetry install

      - name: Install latest drunc and druncschema
        if: ${{ inputs.use_develop }}
        run: |
          pip install git+https://github.com/DUNE-DAQ/druncschema.git@develop
          pip install git+https://github.com/DUNE-DAQ/drunc.git@develop

      - name: Test building the docs
        run: poetry run mkdocs build --strict

      - name: Run tests
        if: ${{ !cancelled() }}
        run: poetry run pytest --cov-report=xml

      - name: Upload coverage to Codecov
        if: github.event.pull_request.user.login != 'dependabot[bot]' && github.event.pull_request.user.login != 'pre-commit-ci[bot]'
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
