name: Run MQST

on:
  never-ever:

jobs:
  install_and_test:

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    container:
      image: ghcr.io/dune-daq/nightly-release-alma9:development_v5

    steps:
      - name: Install SSH and run the daemon
        run: |
          dnf install openssh-server
          dnf install openssh-clients
          systemctl start sshd
          systemctl enable sshd
          ssh localhost echo "SSH is working"

      - name: Set up dev nightly
        run: |
          mkdir nightly
          cd nightly
          source /cvmfs/dunedaq.opensciencegrid.org/setup_dunedaq.sh
          setup_dbt latest_v5
          dbt-create -n last_fddaq
          cd NFD_DEV*
          source env.sh
          dbt-build
          dbt-workarea-env

      - name: Install druncschema and drunc
        run: |
          cd nightly/NFD_DEV* || true
          source env.sh
          python -m pip install --upgrade pip
          git clone https://github.com/DUNE-DAQ/druncschema.git -b ${{ github.head_ref }} ||  git clone https://github.com/DUNE-DAQ/druncschema.git
          git clone https://github.com/DUNE-DAQ/drunc.git -b ${{ github.head_ref }}
          cd druncschema
          pip install .
          cd -
          cd drunc
          pip install .
          echo "DRUNC_DIR=$(pwd)" >> $GITHUB_ENV

      - name: Test with MQST
        run: |
          cd nightly/NFD_DEV* || true
          source env.sh
          daqsystemtest_integtest_bundle.sh -l 0