name: Test in stable

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/ci.yml
    with:
      python_version: '3.10'
      use_develop: false
